services:
  # 1. BASE DE DATOS (PostgreSQL)
  database:
    image: postgres:16
    container_name: oldschool_db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data # Persistencia de datos
    ports:
      - "5433:5432" # Puerto externo 5433 para no chocar con otros postgres
    networks:
      - oldschool-network

  # 2. BACKEND (Spring Boot)
  backend:
    build: ./backend
    container_name: oldschool_api
    restart: always
    depends_on:
      - database
    environment:
      DB_HOST: database
      DB_PORT: 5432
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      
      # Configuración App
      SERVER_PORT: 8080
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
      
      # Servicios Externos
      SENTRY_DSN: ${SENTRY_DSN}
      SENTRY_DEBUG: "false"
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      
    ports:
      # Mapea puerto del .env (8085) al interno (8080)
      - "${PORT_BACKEND_EXTERNO}:8080"
    volumes:
      - ./uploads:/app/uploads # Persistencia de imágenes
      - ./logs:/app/logs       # Persistencia de logs
    networks:
      - oldschool-network

  # 3. FRONTEND (Angular)
  frontend:
    build: ./frontend
    container_name: oldschool_web
    restart: always
    depends_on:
      - backend
    ports:
      # Mapea puerto del .env (80) al interno (80)
      - "${PORT_FRONTEND_EXTERNO}:80"
    networks:
      - oldschool-network

volumes:
  pgdata:

networks:
  oldschool-network:
    driver: bridge